# Generated by Django 4.2.19 on 2025-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_valid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
