# Generated by Django 4.2.19 on 2025-03-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makebooking',
            name='name',
        ),
    ]
