# Generated by Django 4.2.19 on 2025-02-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Starter', 'Starter'), ('Side', 'Side'), ('Dessert', 'Dessert'), ('Main', 'Main'), ('Drink', 'Drink')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')])),
            ],
        ),
    ]
